-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-2",
    mode = "3840x2160@60",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "DP-4",
    mode = "2560x1440@165",
    position = "3840x0",
    scale = "1",
})

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

--monitor=HDMI-A-2,disable
